# Generated by Django 4.1.7 on 2023-02-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
