# Generated by Django 4.1.7 on 2023-02-26 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_bill_product_price_alter_bill_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='price',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
